# Generated by Django 4.0.6 on 2022-08-06 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='desc',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
