# Generated by Django 4.0.6 on 2022-08-06 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_cart_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='desc',
        ),
    ]
