# Generated by Django 4.0.6 on 2022-08-06 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_cart_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='catId',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='prodId',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
        migrations.DeleteModel(
            name='Discount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='catId',
        ),
        migrations.RemoveField(
            model_name='order',
            name='prodId',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
