# Generated by Django 4.0.6 on 2022-08-07 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_cart_shelly'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='shelly',
        ),
    ]
