# Generated by Django 4.0.6 on 2022-08-08 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_cart_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='amount',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_amount', to='base.cart'),
        ),
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_total_price', to='base.cart'),
        ),
    ]
