# Generated by Django 4.0.6 on 2022-08-08 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_order_amount_order_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='amount',
            field=models.ForeignKey(db_column='amount', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_amount', to='base.cart'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.ForeignKey(db_column='total_price', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_total_price', to='base.cart'),
        ),
    ]
