# Generated by Django 4.0.6 on 2022-08-24 14:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='createdTime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
