# Generated by Django 4.0.6 on 2022-12-24 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_alter_profile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetail',
            old_name='prod',
            new_name='product',
        ),
    ]
