# Generated by Django 4.0.6 on 2022-12-24 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_rename_prod_orderdetail_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='total_price',
            new_name='order_total_price',
        ),
    ]
