# Generated by Django 4.0.6 on 2022-12-24 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0030_alter_orderdetail_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_total_price',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='total_price',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
