# Generated by Django 4.0.6 on 2023-01-18 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0033_alter_order_createdtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='createdTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
