# Generated by Django 4.0.6 on 2023-01-20 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0034_alter_order_createdtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='createdTime',
            field=models.DateTimeField(verbose_name='%Y-%d-%m'),
        ),
    ]
