# Generated by Django 4.0.6 on 2023-01-20 14:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0035_alter_order_createdtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='createdTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
