# Generated by Django 4.0.6 on 2023-01-20 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0036_order_date_alter_order_createdtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='order_total_price',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, related_name='order_total_p', to='base.order'),
        ),
    ]
