# Generated by Django 4.0.6 on 2023-01-20 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0037_orderdetail_order_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='order_total_price',
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='base.order'),
        ),
    ]
