# Generated by Django 4.0.6 on 2023-01-20 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0039_alter_orderdetail_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='sss',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=100),
        ),
    ]
