# Generated by Django 4.0.6 on 2023-01-20 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0041_remove_orderdetail_sss'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_total_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=100, unique=True),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='order_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.order', to_field='order_total_price'),
        ),
    ]
