# Generated by Django 4.0.6 on 2023-01-20 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0044_alter_order_order_total_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
