# Generated by Django 4.0.6 on 2023-01-20 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0045_orderdetail_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='order_total_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=100),
        ),
    ]
